### ISSUE TITLE
how to obtain .conll

### ISSUE THREAD

**Issue by yifding** [lephong/wnel#1]
Hey Phong, i am trying to apply wnel on a new dataset. I noticed that most data is developed on deep-ed and there is the CONLL format which is included in wnel but not in deep-ed.  Just want to ask how do you obtain the .conll file and would you able to release the code?

**Comment by lephong** [comment]
So sorry to say that I no longer maintain the code. I also didn't keep code for preprocessing after moving to the current workplace. 

For CONLL format, you can use available libs e.g corenlp.

**Comment by yifding** [comment]
Thank you, just find out that without NER label, wnel can still obtain some fair performance. 
Good luck on your new job, Close it now.
